camera_name: 'USB30W01'
camera_frame_id: 'usb_cam'
camera_vendor_id: '0c45'
camera_model_id: '62f0'

# camera parameters, range: 0-255, -1 for "leave alone"
auto_white_balance: true
autoexposure: true
autofocus: false
brightness: -1
contrast: -1
exposure: 100
focus: -1
framerate: 2
gain: -1
image_width: 640
image_height: 480
io_method: 'mmap' # mmap/read/userptr
pixel_format: 'yuyv' # yuyv/uyvy/mjpeg/yuvmono10/rgb24
saturation: -1
sharpness: -1
white_balance: 4000
