camera_name: 'USBFHD01M_1080p'
camera_frame_id: 'usb_cam'
camera_vendor_id: '05a3'
camera_model_id: '9230'

# camera parameters, 0-255, -1 "leave alone"
auto_white_balance: false
autoexposure: false
autofocus: false
brightness: -1
contrast: -1
exposure: 100
focus: -1
framerate: 60
gain: -1
io_method: 'mmap' # mmap/read/userptr
image_width: 1920
image_height: 1080
pixel_format: 'yuyv' # yuyv/uyvy/mjpeg/yuvmono10/rgb24
saturation: -1
sharpness: -1
white_balance: 4000
